### ISSUE TITLE
Incorrect style for disabled items in OverflowMenu when hover.

### ISSUE THREAD

**Issue by Chengxuan** [carbon-design-system/carbon-themes#32]
## Detailed description
Hovering on a disabled item in OverflowMenu component uses the same style as on an enabled item:
![tile-disabled](https://user-images.githubusercontent.com/5425125/37471595-126866a0-2862-11e8-9bee-ad0b9b1d0b4a.png)

In the image above, both `Edit` and `Delete` option are disabled in the menu and the cursor is hovering on `Delete`.

**Comment by aagonzales** [comment]
Changes needed:
- [ ] Remove hover states from disabled item in menu
- [ ] Design task: re-evaluate system text disabled state. Decrease opacity more?

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-components #659](https://github.com/carbon-design-system/carbon-components/issues/659) via [**ZenHub**](https://www.zenhub.com/)
