### ISSUE TITLE
$button-height in Watson Themes

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-themes#5]
I wrote a comment at
https://github.com/carbon-design-system/carbon-themes/commit/ab6431b22a1a02f4928cb3b6ec2231ce4df1a9d2.

In the Watson Theme, I'm wondering why `$button-height` is `32px` rather than `2rem`.

**Comment by tw15egan** [comment]
Thanks for catching that! Feel free to make a PR, or I can update it when I get back on Monday
