### ISSUE TITLE
Duplicate ui color in Watson Theme

### ISSUE THREAD

**Issue by krbrewer** [carbon-design-system/carbon-themes#6]
In the current Watson theme both `$ui-03` and `$ui-04` are set to `#eaeaea`.

https://github.com/carbon-design-system/carbon-themes/blob/ab6431b22a1a02f4928cb3b6ec2231ce4df1a9d2/themes/watson.scss

**Comment by tw15egan** [comment]
These were the colors provided to me. Should this be changed to a different color?
